### ISSUE TITLE
MPI error when tried to create a new communication

### ISSUE THREAD

**Issue by zhangruoyao68** [myousefi2016/Cahn-Hilliard-MPI#2]
Hi,

Thank you for sharing the code! I built the latest version of VTK with MPI enabled and compiled the code with
  1) cmake/3.x
  2) intel-mkl/2020.1/1/64
  3) intel/19.1/64/19.1.1.217
  4) openmpi/intel-17.0/3.1.3/64

Compilation was a success. However, running the program gave me following errors, which have bothered me for a while and could not figure out why.

```
[tiger-i25c1n21:14255] *** An error occurred in MPI_Cart_create
[tiger-i25c1n21:14255] *** reported by process [4060962525,0]
[tiger-i25c1n21:14255] *** on communicator MPI_COMM_WORLD
[tiger-i25c1n21:14255] *** MPI_ERR_ARG: invalid argument of some other kind
[tiger-i25c1n21:14255] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[tiger-i25c1n21:14255] ***    and potentially your MPI job)
Processor name = tiger-i25c1n21
```

Thanks!

**Comment by myousefi2016** [comment]
Hi @zhangruoyao68 Thanks for your interest in [Cahn-Hilliard-MPI](https://github.com/myousefi2016/Cahn-Hilliard-MPI) code. I'm happy that you were able to compile the code successfully, so I hope I can help you to make it run as well.

My first guess about the error that you are seeing is that probably there is a discrepancy between the number of processors that you gave to MPI and how you decomposed the domain along X, Y, and Z directions. Did you use the command that is given in the README for running the code?

```
mpirun -np #nprocs ./Cahn-Hilliard-MPI #decompX #decompY #decompZ
``` 

In fact, the error that you are seeing basically says that you are trying to create a communication with number of processors that are not available to MPI. Have you checked to see if `#nprocs = #decompX * #decompY * #decompZ` in your running command? How about running the program in this way:

```
mpirun -np 1 ./Cahn-Hilliard-MPI 1 1 1
```

If you are able to run the above command without error, my guess might be true and you need to make sure the number of processors is equal to multiplication of number of domain decompositions along X, Y, and Z directions. I hope it helps. Please let me know if you encountered any other error or issue.

**Comment by zhangruoyao68** [comment]
Hi @myousefi2016 ,

Thank you very much for helping out! This is exactly what I was doing wrong. I misunderstood the meaning of #decompX,Y,Z in your explanation.

Best,

**Comment by myousefi2016** [comment]
@zhangruoyao68  I'm glad that it works now! Thanks for your interest and attention!
